version: '3'
services:
  jaeger: 
    image: jaegertracing/all-in-one:1.8
    ports:
     - "5775:5775/udp"
     - "6831:6831/udp"
     - "6832:6832/udp"
     - "5778:5778"
     - "16686:16686"
     - "14268:14268"
     - "9411:9411"
    environment:
     - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      mp-net:
        ipv4_address: 172.18.0.6    
    
  mp-speaker:
    build: ./mp-speaker
    ports:
     - "8080:8080"
     - "5006:5006"
    depends_on:
     - jaeger
     - db-speaker
    networks:
      mp-net:
        ipv4_address: 172.18.0.3 
    links:
     - jaeger
    environment: 
     - JAEGER_AGENT_HOST=jaeger 
     - JAEGER_SERVICE_NAME=speaker
     - JAEGER_REPORTER_LOG_SPANS=true
     - JAEGER_SAMPLER_TYPE=const
     - JAEGER_SAMPLER_PARAM=1  
    volumes:
     - ./config:/etc/mp-speaker/config
  mp-subject:
    build: ./mp-subject
    ports:
     - "8081:8080"
     - "5007:5006"
    depends_on:
     - jaeger
     - db-subject
    networks:
       mp-net:
         ipv4_address: 172.18.0.5
    links:
     - jaeger
    environment: 
     - JAEGER_AGENT_HOST=jaeger 
     - JAEGER_SERVICE_NAME=subject
     - JAEGER_REPORTER_LOG_SPANS=true
     - JAEGER_SAMPLER_TYPE=const
     - JAEGER_SAMPLER_PARAM=1
    volumes:
     - ./config:/etc/mp-subject/config
  db-speaker:
    image: mongo:4.1.5-xenial
    ports: 
     - "27017:27017"
    networks:
       mp-net:
        ipv4_address: 172.18.0.2

  db-subject:
    image: mongo:4.1.5-xenial
    ports: 
     - "27018:27017"
    networks:
      mp-net:
         ipv4_address: 172.18.0.4
  app-web:
    build: ./app-web
    ports:
     - "80:8080"
    networks:
      mp-net:
        ipv4_address: 172.18.0.7


networks:
    mp-net:
        driver: bridge
        ipam:
          config:
            - subnet: 172.18.0.0/16
