version: '3'
services:
  mp-speaker:
    build: ./mp-speaker
    ports:
     - "8080:8080"
    networks:
      mp-net:
        ipv4_address: 172.18.0.3    
    volumes:
     - ./config:/etc/mp-speaker/config
  mp-subject:
    build: ./mp-subject
    ports:
     - "8081:8080"
     - "5006:5006"
    networks:
       mp-net:
         ipv4_address: 172.18.0.5

    volumes:
     - ./config:/etc/mp-subject/config
  db-speaker:
    image: mongo:4.1.5-xenial
    ports: 
     - "27017:27017"
    networks:
       mp-net:
        ipv4_address: 172.18.0.2

  db-subject:
    image: mongo:4.1.5-xenial
    ports: 
     - "27018:27017"
    networks:
      mp-net:
         ipv4_address: 172.18.0.4

networks:
    mp-net:
        driver: bridge
        ipam:
          config:
            - subnet: 172.18.0.0/16
